"""Bidirectional Arrow IPC conformance (issue #21).

"JS writes -> Python reads": js_written.arrow was generated by
fixtures/generate_js_fixtures.mjs using mallory-frame-arrow's Frame.toIPC().
"Python writes -> JS reads": py_written.arrow is generated by this
directory's generate_py_fixtures.py; a companion JS-side test in
packages/frame-arrow/test/interop-python.test.ts reads it back and checks
against py_written_expected.json.

Comparison is schema + values (via the shared *_expected.json fixtures),
not a byte-diff -- matches this repo's established conformance style (see
docs/spikes/arrow-parity.md's own methodology).
"""

import json
import tempfile
from pathlib import Path

import pandas as pd
import pyarrow as pa
import pyarrow.ipc as ipc

from mallory_interop import read_ipc, write_ipc

FIXTURES = Path(__file__).parent / "fixtures"


def _rows_as_plain(df: pd.DataFrame) -> list[dict]:
    """pd.ArrowDtype columns (from read_ipc's types_mapper) need pd.isna, not `is None`,
    to detect nulls, and their scalar values need normalizing to compare against
    the plain-JSON expected fixtures."""
    records = []
    for _, row in df.iterrows():
        record = {}
        for col in df.columns:
            v = row[col]
            record[col] = None if pd.isna(v) else (bool(v) if df[col].dtype.kind == "b" else v)
        records.append(record)
    return records


def test_reads_js_written_ipc_matching_expected():
    expected = json.loads((FIXTURES / "js_written_expected.json").read_text())
    df = read_ipc(str(FIXTURES / "js_written.arrow"))
    assert list(df.columns) == expected["columns"]
    actual_rows = _rows_as_plain(df)
    assert actual_rows == expected["rows"]


def test_reads_own_py_written_ipc_matching_expected():
    expected = json.loads((FIXTURES / "py_written_expected.json").read_text())
    df = read_ipc(str(FIXTURES / "py_written.arrow"))
    assert list(df.columns) == expected["columns"]
    actual_rows = _rows_as_plain(df)
    assert actual_rows == expected["rows"]


def test_write_then_read_back_round_trips_exactly():
    df = pd.DataFrame(
        {
            "x": pd.array([10, 20, 30], dtype="Int64"),
            "y": pd.array([1.1, None, 3.3], dtype="Float64"),
        }
    )
    with tempfile.TemporaryDirectory() as tmp:
        path = str(Path(tmp) / "roundtrip.arrow")
        write_ipc(df, path)
        back = read_ipc(path)
        assert list(back.columns) == ["x", "y"]
        assert back["x"].tolist() == [10, 20, 30]
        assert back["y"].tolist()[0] == 1.1
        assert pd.isna(back["y"].tolist()[1])
        assert back["y"].tolist()[2] == 3.3


def test_write_then_read_back_preserves_nan_as_nan_not_null():
    """issue #103: a genuine NaN in a plain (non-nullable-extension) float
    column must round-trip as NaN, not get silently coerced to an Arrow
    null -- those are different things (not-a-number vs. missing), and
    pyarrow's default `Table.from_pandas` conversion collapses them."""
    df = pd.DataFrame({"y": [1.1, float("nan"), 3.3]})
    with tempfile.TemporaryDirectory() as tmp:
        path = str(Path(tmp) / "nan_roundtrip.arrow")
        write_ipc(df, path)

        # The written file itself must hold a real NaN, not an Arrow null,
        # for the affected value.
        with pa.memory_map(path, "rb") as source:
            table = ipc.open_file(source).read_all()
        assert table.column("y").null_count == 0

        back = read_ipc(path)
        values = back["y"].tolist()
        assert values[0] == 1.1
        assert values[2] == 3.3
        nan_value = values[1]
        # A real NaN is falsy under `is pd.NA` and `!=` itself; a null read
        # back through read_ipc's `pd.ArrowDtype` types_mapper would be
        # `pd.NA` instead, which fails the float-NaN self-inequality check.
        assert nan_value is not pd.NA
        assert nan_value != nan_value  # NaN is the only value unequal to itself
